STATE_LINKING = 0;
STATE_RUNNING = 1;

ID_STOP = -1
ID_SETUP = 0
ID_START = 1
ID_KEY = 2
ID_MOUSE_MOVE = 3
ID_MOUSE_CLICK = 4

MOUSE_BUTTON_LEFT = 1
MOUSE_BUTTON_MIDDLE = 2
MOUSE_BUTTON_RIGHT = 3
MOUSE_BUTTON_WHEEL_UP = 4
MOUSE_BUTTON_WHEEL_DOWN = 5
